// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHp0isTY7fUqQqZoiMSEFTm6NtEiGwR0',
    appId: '1:822415255163:web:64ad38b1d783da2875e4de',
    messagingSenderId: '822415255163',
    projectId: 'zhiyuan-intern-portal',
    authDomain: 'zhiyuan-intern-portal.firebaseapp.com',
    storageBucket: 'zhiyuan-intern-portal.firebasestorage.app',
    measurementId: 'G-E7C89914TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5YDn0EYqzRVK-OCyvLI8JS_HtiEGYVw',
    appId: '1:822415255163:android:153ebcaa9ce2bbc575e4de',
    messagingSenderId: '822415255163',
    projectId: 'zhiyuan-intern-portal',
    storageBucket: 'zhiyuan-intern-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwNbLugbOx2d_jxtwN2gGHfLajWmCZd0',
    appId: '1:822415255163:ios:deab217ff10d99ab75e4de',
    messagingSenderId: '822415255163',
    projectId: 'zhiyuan-intern-portal',
    storageBucket: 'zhiyuan-intern-portal.firebasestorage.app',
    iosBundleId: 'com.zhiyuan.zhiyuanInternPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwNbLugbOx2d_jxtwN2gGHfLajWmCZd0',
    appId: '1:822415255163:ios:deab217ff10d99ab75e4de',
    messagingSenderId: '822415255163',
    projectId: 'zhiyuan-intern-portal',
    storageBucket: 'zhiyuan-intern-portal.firebasestorage.app',
    iosBundleId: 'com.zhiyuan.zhiyuanInternPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFHp0isTY7fUqQqZoiMSEFTm6NtEiGwR0',
    appId: '1:822415255163:web:30544f608907c13375e4de',
    messagingSenderId: '822415255163',
    projectId: 'zhiyuan-intern-portal',
    authDomain: 'zhiyuan-intern-portal.firebaseapp.com',
    storageBucket: 'zhiyuan-intern-portal.firebasestorage.app',
    measurementId: 'G-LDKYEMF7VG',
  );

}